### ISSUE TITLE
gamify after answer

### ISSUE THREAD

**Issue by marvelbark2** [matt-daneshvar/laravel-survey#10]
Hello 
please is there anyway to migrate your package with this package https://github.com/qcod/laravel-gamify i already use it and i want to use it with your package
i tried this : 
$d = (new Entry)->for($survey)->by(Auth::user())->fromArray($answers)->push();
givePoint(new SurveyAnswered($d));
in the my controller and in push method in entry model i returned to $this 
Could you help me please ?

**Comment by marvelbark2** [comment]
The porblem fixed .
I fixed by replace use Illuminate\Foundation\Auth\User; by use App\User;
and that modification fix a lot of problems 
Thank you so much for this package sir 👍

**Comment by matt-daneshvar** [comment]
Hey @marvelbark2

Thanks for trying out the package! Glad you managed to solve the issue :)

**Comment by marvelbark2** [comment]
if you eant i already make a wizard for sections and management dashboard i can share them use you 
and i can use survey form generator to make survey , to add them to the package
