### ISSUE TITLE
Creating survey with non-authenticated user

### ISSUE THREAD

**Issue by assis-lucas** [matt-daneshvar/laravel-survey#12]
Hello everyone,

I have been trying to using Survey package with authenticated users, and I have already could get this. 
but What I'm asking about, It's removing logged user requirement to do the survey.

This is my: views/vendor/survey/standard.blade.php

`<div class="card">
    <div class="card-header bg-white p-4">
        <h2 class="mb-0">{{ $survey->name }}</h2>

        @if(!$eligible)
        Nós aceitamos apenas
        <strong>{{ $survey->limitPerParticipant() }}
            {{ \Str::plural('entrada', $survey->limitPerParticipant()) }}</strong>
        por participante.
        @endif

        @if($lastEntry)
        Você já enviou as suas respostas <strong>{{ $lastEntry->created_at->diffForHumans() }}</strong>.
        @endif

    </div>
    @if(!$survey->acceptsGuestEntries() && auth()->guest())
    <div class="p-5">
        Porfavor faça o <a href="{{ route('login') }}">login</a> para fazer essa pesquisa.
    </div>
    @else
    @foreach($survey->sections as $section)
    @include('survey::sections.single')
    @endforeach

    @foreach($survey->questions()->withoutSection()->get() as $question)
    @include('survey::questions.single')
    @endforeach

    @if($eligible)
    <button class="btn btn-primary">Enviar</button>
    @endif
    @endif
</div>`

**Comment by matt-daneshvar** [comment]
Hi Lucas,

To allow guest entries, you can add the `accept-guest-entries` flag to the survey settings:
```php
Survey::create(['settings' => ['accept-guest-entries' => true]]);
```

I'm closing this as the issue has been stale for some time. Let me know if the above settings doesn't fix the issue and you need more help.
