### ISSUE TITLE
using 2 times Question::class in Answer model

### ISSUE THREAD

**Issue by danito** [matt-daneshvar/laravel-survey#17]
Hi,
Your app seems interesting, but looking at the source code I stumbled upon some strange entry.
In the Answer model, you're using the Question::class in place of the Entry::class 
https://github.com/matt-daneshvar/laravel-survey/blob/9982df3c2b5e1d204328cc4a778598d222d9704a/src/Models/Answer.php#L37
Not sure if this is a bug or a feature.

**Comment by matt-daneshvar** [comment]
Hi Daniel, this does look like a bug. Thank you for catching this. I'll push up a fix shortly.
