### ISSUE TITLE
How do you make it to process the survey?

### ISSUE THREAD

**Issue by Arizaser** [matt-daneshvar/laravel-survey#18]
I now know how to make the survey appear o the list, but how do you make the controller to process the survey and add a new entry when the submit button is clicked?

**Comment by matt-daneshvar** [comment]
Hi @Arizaser - Thanks for trying the package. Here's an example of a controller storing an `Entry`: 
```php
class SurveyEntriesController extends Controller
{
    public function store(Survey $survey, Request $request)
    {
        $answers = $this->validate($request, $survey);
        
        (new Entry)->for($survey)->fromArray($answers)->push();
    }
}
```

You can see more examples under the [Creating an Entry](https://github.com/matt-daneshvar/laravel-survey#creating-an-entry) section. 

Let me know if this solves it for you or if you need help with anything else.
