### ISSUE TITLE
Missing config?

### ISSUE THREAD

**Issue by programmin1** [matt-daneshvar/laravel-survey#24]
Migrating: 2021_12_18_180211_create_answers_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' 

Seems there is a missing config/Survey.php? for config('survey.database.tables.answers')

**Comment by programmin1** [comment]
https://github.com/matt-daneshvar/laravel-survey/blob/master/config/survey.php
was not included when I ran the instructions in readme.

**Comment by nawawi** [comment]
> https://github.com/matt-daneshvar/laravel-survey/blob/master/config/survey.php was not included when I ran the instructions in readme.
> 
> Furthermore one must "php artisan config:clear" after.

try run:
`php artisan vendor:publish --provider="MattDaneshvar\Survey\SurveyServiceProvider" --tag="config"`

**Comment by matt-daneshvar** [comment]
@programmin1 thanks for raising this. I think [Laravel generally doesn't recommend caching configurations on your development environment](https://laravel.com/docs/8.x/configuration#configuration-caching): 

> You should typically run the php artisan config:cache command as part of your production deployment process. The command should not be run during local development as configuration options will frequently need to be changed during the course of your application's development.

If this is something one still prefers to do would it be reasonable to expect that they should always clear their configuration cache every time they install a new package?
