### ISSUE TITLE
Fails with mariadb

### ISSUE THREAD

**Issue by programmin1** [matt-daneshvar/laravel-survey#25]
Migrating: 2021_12_18_180211_create_questions_table

...

PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `rules` json null, `created_at` timestamp null, `updated_at` timestam' at line 1")

It seems this doesn't work with MariaDB, which is fairly common on Linux servers.

**Comment by nawawi** [comment]
It seems to work with MariaDB 10.3.28. Make sure the config file config/survey.php exist first.

![image](https://user-images.githubusercontent.com/1203635/146901094-0c2ccfc5-f0ab-4a29-ba18-4a6ac2f9dfd7.png)

![image](https://user-images.githubusercontent.com/1203635/146901886-1d0ce2f9-3ed8-43e5-897f-5f201c19c64b.png)

**Comment by matt-daneshvar** [comment]
Hi @programmin1, thank you for checking out this package. I suspect that this error, as @nawawi pointed out, shouldn't occur with the more recent versions of MariaDB. Reading through [their docs](https://mariadb.com/kb/en/json-data-type/):

> The JSON alias was added in MariaDB 10.2.7. This was done to make it possible to use JSON columns in statement based replication from MySQL to MariaDB and to make it possible for MariaDB to read mysqldumps from MySQL.

If you're still on an older version, one workaround will be to: 
1. Publish the migrations of the package: 
```
php artisan vendor:publish --provider="MattDaneshvar\Survey\SurveyServiceProvider" --tag="migrations"
```
2. Change all usages of `$table->json()` to `$table->longText()`. 

I'm closing this issue for now, but please feel free to comment for more dicussion if the information above doesn't get you past the errors you're facing.
