### ISSUE TITLE
How to add custom column to Entry model

### ISSUE THREAD

**Issue by dzymail** [matt-daneshvar/laravel-survey#27]
Hi, 
I want to add 2 fields to the Entry model, one to save the fingerprint of the browser, and the other to save the converted time. This way I can identify different Guest users roughly. I have solved the way of generating fingerprints, and adding database fields is not a problem. 
My question are, what is the proper way to define custom fields of Entry model? how to save the data of new fields when user submit answers?
or may be i ask wrong question, should i add fields to other model?

**Comment by matt-daneshvar** [comment]
Hi @dzymail - The `Entry` class is a standard Eloquent model, which makes it possible to set attributes in many different ways. One approach is to use the `setAttribute` method and chain it fluently when creating your new `Entry` model. Here is an example: 
```php
Entry::make()
  ->for($survey)
  ->fromArray($answers)
  ->setAttribute('fingerprint', $fingerprint)
  ->setAttribute('another_key', $anotherValue)
  ->push();
```
Let me know if this answers your question.

**Comment by dzymail** [comment]
Thanks. it‘s helpful, you saved my day again. :)
