### ISSUE TITLE
How to create a question with select and options?

### ISSUE THREAD

**Issue by Visage982** [matt-daneshvar/laravel-survey#28]
To create a question that is a dropdown list and the user can select one of them

**Comment by matt-daneshvar** [comment]
Hi @Visage982, thanks for trying out this package. This may be a bit late, but still sharing this for the benefit of anyone who may come across this thread. 

To create a new question type:

1\. Publish the views that come with this package:
```
php artisan vendor:publish --provider="MattDaneshvar\Survey\SurveyServiceProvider" --tag="views"
```

2\. Create a template for the new question type (let's call it `select`) under:
```
 <your-views-director>/vendor/survey/questions/types/select.php
```
The impelementation for this could be quite similar to the existing question types that come with the package (see `radio` and `multiselect`).

3\. Configure your survey to use your new question type:
```php
$two->questions()->create([
  'content' => 'How do you like this product?',
  'type' => 'radio-and-text',
  'options' => ['A lot', 'A bit', 'Not at all']
]); 
```
