### ISSUE TITLE
How get the Report?

### ISSUE THREAD

**Issue by starking8b** [matt-daneshvar/laravel-survey#37]
MANY THANKS  FOR AWSOME PACKAGE, I integrated it in my system  , but as I see in the base.blade.php there is variable name $report , but this variable not return any things,  can  u please guide me to generate the report please

**Comment by matt-daneshvar** [comment]
Hi @starking8b, thanks for using the package. The `$report` variable in `base.blade.php` is a placeholder that various question types fill differently to display their results to participants who have already submitted the survey. 

If you notice `number.blade.php`, for example, it fills the report slot with the average of all values submitted for a question:
```blade
@slot('report')
    @if($includeResults ?? false)
        {{ number_format((new \MattDaneshvar\Survey\Utilities\Summary($question))->average()) }} (Average)
    @endif
@endslot
```

Here's an example of how this shows up:
  
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/10030505/182067179-09907712-c858-424a-aa04-52fbf53d0a8f.png">

This only works if: 
- The user who submits the survey is authenticated.
- The `Entry` is correctly [associated to that user](https://github.com/matt-daneshvar/laravel-survey#by-a-specific-user).
