### ISSUE TITLE
Guest Submit + Special Parameters ? 

### ISSUE THREAD

**Issue by m7mdcc** [matt-daneshvar/laravel-survey#38]
Hi . is it possible limit-per-participant with guest submit by passing unique id to survey then the page refresh it's self to setting this ID as hidden input ? 

also could we pass special parameter like the name of the participant to survey as " Welcome Firstname Lastname !"  ?

Thanks for this project

**Comment by matt-daneshvar** [comment]
Hi @m7mdcc, thanks for using the package.

I haven't explored these before, but here are a few ideas on how you may be able to achieve them in your project:

### Passing additional parameters 

One way to do this may be to [override the views](https://github.com/matt-daneshvar/laravel-survey#customizing-the-views) that come with the package. To start, I would first publish those views:

```
php artisan vendor:publish --provider="MattDaneshvar\Survey\SurveyServiceProvider" --tag="views"
```

Then update `resources/views/vendor/survey/standard.blade.php`  to include a welcome message:
```blade
<div class="card">
    <div class="card-header bg-white p-4">
        <h1>Welcome, {{ $firstName }}</h1>
        <h2 class="mb-0">{{ $survey->name }}</h2>
...
```

And finally, update my parent view (the one that includes the `survey::standard` view) to pass in additional parameters:
```blade
@include('survey::standard', ['survey' => $survey, 'firstName' => auth()->user()->name])
```

### Changing limit-per-participant behaviour
To do this, I would create a new `Entry` class in my app that extends the package's `Entry` model. Then override a few specific methods, including the `validateMaxEntryPerUserRequirement` method, to allow guest participants:
```php

namespace App\Models;

use MattDaneshvar\Survey\Models\Entry as BaseEntry;

class Entry extends BaseEntry {
  public function validateMaxEntryPerUserRequirement() {
    // Your new implementation
  }
}

```

If you're thinking of using a hidden input within the survey, you may follow the same strutucre as above to pass in additional parameters to the survey view. 

Let me know if these work for you or if you encounter any issues.
