### ISSUE TITLE
Multi Select type does load check boxes it loads text box

### ISSUE THREAD

**Issue by zaloAustine** [matt-daneshvar/laravel-survey#40]
$valid = $request->validate([
                    'options1s' => 'required',
                    'options2s' => 'required',
                    'options3s' => 'required',
                    'options4s' => 'required'
                ]);

                    $survey->questions()->create([
                        'content' => $question,
                        'type' => 'mutliselect',
                        'options' => [$request->options1s, $request->options2s, $request->options3s, $request->options4s]
                    ]);

While building the survey form the type "mutliselect" doesn't work as expected

**Comment by zaloAustine** [comment]
Found out the name in the documentation is mis directing "mutliselect"

**Comment by matt-daneshvar** [comment]
Hi @zaloAustine, thanks for using the package. 

I understand the name "multiselect" for the functionality provided can be misleading; this was briefly debated in #22 too. We can definitely rename it to something else in future versions.

I'm not sure if I quite understand what you were trying to achieve with this snippet: 
```
'options' => [$request->options1s, $request->options2s, $request->options3s, $request->options4s]
```

But I'd generally recommend [creating your own custom question types](https://github.com/matt-daneshvar/laravel-survey#creating-new-question-types) if the question types coming with the package don't meet your needs.
