### ISSUE TITLE
Validation example for multiselect type of question ?

### ISSUE THREAD

**Issue by Forsakenrox** [matt-daneshvar/laravel-survey#45]
Hi, If you don't mind, could you show an example of multiselect question validation?
`'rules' => ['nullable', 'array']
`
i want validate values inside array too, thx.

**Comment by matt-daneshvar** [comment]
Hi @Forsakenrox, thanks for using Laravel Survey.

One option is to use the [in:foo,bar,...](https://laravel.com/docs/10.x/validation#rule-in) rule to specify all possible values. For example, if your question reads "What's your favorite color?" and accepts "blue", "black", and "orange", you can use:
```
'rules' => ['nullable', 'array', 'in:blue,black,orange'] 
```
Does this work for your use case?
