### ISSUE TITLE
No hint path defined for [survey]

### ISSUE THREAD

**Issue by kylemabaso** [matt-daneshvar/laravel-survey#46]
Hi.

I get an error 500 on the live app. It works perfectly fine on Valet.

When I check the logs, the message says:

> [2023-04-23 02:30:26] production.ERROR: No hint path defined for [survey]. (View: /home/forge/domain/resources/views/admin/surveys/show.blade.php) {"userId":10,"exception":"[object] (Illuminate\View\ViewException(code: 0): No hint path defined for [survey]. (View: /home/forge/domain/resources/views/admin/surveys/show.blade.php) at /home/forge/domain/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:112)

`@include('survey::standard', ['survey' => $survey])
`

**Comment by matt-daneshvar** [comment]
Apologies for the late response, Kyle. 

Posting an answer in case others end up here. This sounds like a configuration issue in your production or the package not being correctly installed. A couple of ideas I'd try: 

- Ensure that the package is physically installed by getting inside your `vendor` directory in your production environment.
- Clear or update your configuration cache by running either `php artisan config:clear` or `php artisan config:cache` respectively.
