### ISSUE TITLE
How to show view

### ISSUE THREAD

**Issue by narendraraghuwanshi** [matt-daneshvar/laravel-survey#5]
I want to show view but you not describe which variable i have to pass in view and how your pagination work

**Comment by matt-daneshvar** [comment]
Hi @narendraraghuwanshi. Thanks for trying `laravel-survey`. I just bumped up the package version to address the question you asked. Please change the package version from `^0.1.1` to `0.1.2` (or to `dev-master`) in your `composer.json` file and run `composer update` before continuing with this answer.

The package comes with some demo views built inside. Once you have created your `Survey` instance, you may include the `survey::standard` partial inside any of your views and pass along your `Survey` instance as below:
```blade
@include('survey::standard', ['survey' => $survey])
```

This would render a basic card with all the survey sections and questions inside (as displayed on the [readme page](https://github.com/matt-daneshvar/laravel-survey)). 

You may also publish those demo views:
```bash
php artisan vendor:publish --provider="MattDaneshvar\Survey\SurveyServiceProvider" --tag="views"
```
This would make them available to you under your applications `views` directory under `/vendor/survey`.

The demo views by default don't include pagination, but you should be able to achieve it by some minor tweaks.
