### ISSUE TITLE
Curiosity about the `for` method

### ISSUE THREAD

**Issue by maxacarvalho** [matt-daneshvar/laravel-survey#7]
Hi,

I found your approach really interesting but, I don't understand the `Entry::for(...` method.
It's a non-static method being called as a static one, that will not work I'm afraid.

**Comment by matt-daneshvar** [comment]
Hi @maxacarvalho  

Thank you for checking out this repo! You're right, the correct syntax for creating a new `Entry` is:
```php
(new Entry)->for($survey)->fromArray([
    'q1' => 'Yes',
    'q2' => 5
])->push();
```
I've now updated the documentation accordingly :)
