### ISSUE TITLE
Make form for survey 

### ISSUE THREAD

**Issue by marvelbark2** [matt-daneshvar/laravel-survey#9]
Hello i made a blade with including the survey but how to make a form to collect the entries and push them in db ?

**Comment by marvelbark2** [comment]
The problem i got an empty participant_id even i'm logged !!

**Comment by matt-daneshvar** [comment]
Hi @marvelbark2. Thanks for trying out the package! 

There are some guidelines on [creating an entry by a specific user](https://github.com/matt-daneshvar/laravel-survey#by-a-specific-user) in the package docs. When creating your entries, do you specify the user using the `by($user)` function?

**Comment by marvelbark2** [comment]
i fixed by $user = \App\User 
Thank you !
